server.port: 7002
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.example: DEBUG

---
spring.profiles: docker

spring.datasource:
  url: jdbc:mysql://mysql/review-db
  
server.port: 8080