apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dis
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          envFrom:
            - secretRef:
                name: mysql-server-credentials
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 350Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: dis
      spec:
        storageClassName: "fast"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: dis
  name: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - port: 3306