server.port: 7000
server.error.include-message: always

app:
  hotel-service:
    host: localhost
    port: 7001
  location-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003
  room-service:
    host: localhost
    port: 7004

logging:
  level:
    root: INFO
    microservices: DEBUG
